apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    dc: IN
    env: testing

  spec:
    containers:
    - name: "mycontainer"
      image: "httpd"
      volumeMounts:
        - name: myvol
          mountPath: /usr/local/apache2/htdocs
    volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: mypvc